[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true  # ← Add this line
auto_detect_solc = true

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15